export default [
  {
    id: "DSSvW7VLmb",
    model: "Saturn V",
    mass: 2970000,
    payload: {
      description: "Apollo CSM-109 Odyssey, Apollo LM-7 Aquarius, 3 Astronauts",
      weight: 1542,
    },
    telemetry: {
      host: "0.0.0.0",
      port: 4000,
    },
    status: "waiting",
    timestamps: {
      launched: null,
      deployed: null,
      failed: null,
      cancelled: null,
    },
    altitude: 0.0,
    speed: 0.0,
    acceleration: 0.0,
    thrust: 35100000,
    temperature: 0.0,
  },
  // {
  //   id: "9bAWNaUUHz",
  //   model: "Atlas V",
  //   mass: 333000,
  //   payload: {
  //     description: "Some space junk and 4 communication satellites.",
  //     weight: 1109,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4001,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 3827000,
  //   temperature: 0.0,
  // },
  // {
  //   id: "JJbBjCSmc4",
  //   model: "Falcon 9.1",
  //   mass: 505846,
  //   payload: {
  //     description: "Tesla Roadster driving by Starman.",
  //     weight: 923,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4002,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 5885000,
  //   temperature: 0.0,
  // },
  // {
  //   id: "6T5NK8dVft",
  //   model: "Starship",
  //   mass: 150000,
  //   payload: {
  //     description: "9 Astronauts, 200 kgs of dry food and 200 litres of water",
  //     weight: 986,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4003,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 59730000,
  //   temperature: 0.0,
  // },
  // {
  //   id: "B4LXk9mWaR",
  //   model: "Delta IV Heavy",
  //   mass: 733400,
  //   payload: {
  //     description: "Ham the Astrochimp",
  //     weight: 912,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4004,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 12558577,
  //   temperature: 0.0,
  // },
  // {
  //   id: "5SzNqcutXW",
  //   model: "Saturn 1B",
  //   mass: 0.0,
  //   payload: {
  //     description: "Voyager 2 spacecraft",
  //     weight: 1251,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4005,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 1033100,
  //   temperature: 0.0,
  // },
  // {
  //   id: "J3HK7JFvHa",
  //   model: "Vulcan",
  //   mass: 546700,
  //   payload: {
  //     description: "100 liters water, 4 spare parts for space telescope.",
  //     weight: 845,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4006,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 8400000,
  //   temperature: 0.0,
  // },
  // {
  //   id: "FvxKSGLkVC",
  //   model: "Space Shuttle Challenger",
  //   mass: 2300000,
  //   payload: {
  //     description: "7 Astronauts, TDRS-3 communication satellite",
  //     weight: 647,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4007,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 89620000,
  //   temperature: 0.0,
  // },
  // {
  //   id: "FwXALuZnPb",
  //   model: "Long March 3B",
  //   mass: 425800,
  //   payload: {
  //     description: "Some experimental energy weapons, 3 crew",
  //     weight: 984,
  //   },
  //   telemetry: {
  //     host: "0.0.0.0",
  //     port: 4008,
  //   },
  //   status: "waiting",
  //   timestamps: {
  //     launched: null,
  //     deployed: null,
  //     failed: null,
  //     cancelled: null,
  //   },
  //   altitude: 0.0,
  //   speed: 0.0,
  //   acceleration: 0.0,
  //   thrust: 7404000,
  //   temperature: 0.0,
  // },
];
